identifier: ms88sf3_nrf52840
name: MS88SF3 NRF52840
type: mcu
arch: arm
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
ram: 256
flash: 1024
supported:
  - adc
  - usb_device
  - ble
  - ieee802154
  - pwm
  - watchdog
  - gpio
  - i2c
  - spi