identifier: keyboard_h723zg
name: JulienKeyboard
type: keyboard
arch: arm
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
ram: 320
flash: 1024
supported:
  - gpio
  - i2c
  - counter
  - uart
  - spi
  - usb_device
  - usbd
  - rtc
  - kscan
  - nvs