name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3

  upload-hex:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4

      - name: Upload HEX firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-hex
          path: |
            **/zephyr.hex
